# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PDTMainWindow.ui'
#
# Created: Sun Jan 15 13:59:45 2017
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1300, 742)
        Form.setMaximumSize(QtCore.QSize(6500000, 6500000))
        self.gridLayout_4 = QtGui.QGridLayout(Form)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setStatusTip(_fromUtf8(""))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tMain = QtGui.QWidget()
        self.tMain.setObjectName(_fromUtf8("tMain"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tMain)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.frame = QtGui.QFrame(self.tMain)
        self.frame.setMinimumSize(QtCore.QSize(600, 320))
        self.frame.setMaximumSize(QtCore.QSize(600, 380))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_region_defined = QtGui.QLabel(self.frame)
        self.label_region_defined.setGeometry(QtCore.QRect(330, 30, 261, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_region_defined.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_region_defined.setFont(font)
        self.label_region_defined.setLineWidth(3)
        self.label_region_defined.setTextFormat(QtCore.Qt.AutoText)
        self.label_region_defined.setAlignment(QtCore.Qt.AlignCenter)
        self.label_region_defined.setWordWrap(True)
        self.label_region_defined.setObjectName(_fromUtf8("label_region_defined"))
        self.label_properties = QtGui.QLabel(self.frame)
        self.label_properties.setGeometry(QtCore.QRect(320, 170, 281, 111))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_properties.setFont(font)
        self.label_properties.setLineWidth(3)
        self.label_properties.setTextFormat(QtCore.Qt.PlainText)
        self.label_properties.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_properties.setObjectName(_fromUtf8("label_properties"))
        self.groupProtocol = QtGui.QGroupBox(self.frame)
        self.groupProtocol.setGeometry(QtCore.QRect(10, 170, 281, 51))
        self.groupProtocol.setObjectName(_fromUtf8("groupProtocol"))
        self.pLoadExperiment = QtGui.QPushButton(self.groupProtocol)
        self.pLoadExperiment.setGeometry(QtCore.QRect(10, 20, 261, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pLoadExperiment.setFont(font)
        self.pLoadExperiment.setObjectName(_fromUtf8("pLoadExperiment"))
        self.lExperimentFrame = QtGui.QLabel(self.groupProtocol)
        self.lExperimentFrame.setGeometry(QtCore.QRect(10, 60, 91, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lExperimentFrame.setFont(font)
        self.lExperimentFrame.setText(_fromUtf8(""))
        self.lExperimentFrame.setAlignment(QtCore.Qt.AlignCenter)
        self.lExperimentFrame.setObjectName(_fromUtf8("lExperimentFrame"))
        self.lExperimentFrame_2 = QtGui.QLabel(self.groupProtocol)
        self.lExperimentFrame_2.setGeometry(QtCore.QRect(190, 60, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lExperimentFrame_2.setFont(font)
        self.lExperimentFrame_2.setText(_fromUtf8(""))
        self.lExperimentFrame_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lExperimentFrame_2.setObjectName(_fromUtf8("lExperimentFrame_2"))
        self.spinFrameNumber = QtGui.QSpinBox(self.groupProtocol)
        self.spinFrameNumber.setEnabled(True)
        self.spinFrameNumber.setGeometry(QtCore.QRect(110, 60, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinFrameNumber.setFont(font)
        self.spinFrameNumber.setObjectName(_fromUtf8("spinFrameNumber"))
        self.pStart = QtGui.QPushButton(self.frame)
        self.pStart.setGeometry(QtCore.QRect(10, 0, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pStart.setFont(font)
        self.pStart.setCheckable(True)
        self.pStart.setAutoDefault(False)
        self.pStart.setDefault(False)
        self.pStart.setFlat(False)
        self.pStart.setObjectName(_fromUtf8("pStart"))
        self.lcdNumber = QtGui.QLCDNumber(self.frame)
        self.lcdNumber.setGeometry(QtCore.QRect(10, 110, 281, 51))
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.label_status = QtGui.QLabel(self.frame)
        self.label_status.setGeometry(QtCore.QRect(330, 100, 261, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_status.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_status.setFont(font)
        self.label_status.setLineWidth(3)
        self.label_status.setTextFormat(QtCore.Qt.PlainText)
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setWordWrap(True)
        self.label_status.setObjectName(_fromUtf8("label_status"))
        self.edit_full_name = QtGui.QLineEdit(self.frame)
        self.edit_full_name.setGeometry(QtCore.QRect(330, 0, 131, 22))
        self.edit_full_name.setText(_fromUtf8(""))
        self.edit_full_name.setObjectName(_fromUtf8("edit_full_name"))
        self.dateEdit = QtGui.QDateEdit(self.frame)
        self.dateEdit.setGeometry(QtCore.QRect(480, 0, 110, 22))
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.layoutWidget = QtGui.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 290, 581, 33))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pManual = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pManual.setFont(font)
        self.pManual.setObjectName(_fromUtf8("pManual"))
        self.horizontalLayout_4.addWidget(self.pManual)
        self.pResetRegion = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pResetRegion.setFont(font)
        self.pResetRegion.setObjectName(_fromUtf8("pResetRegion"))
        self.horizontalLayout_4.addWidget(self.pResetRegion)
        self.layoutWidget1 = QtGui.QWidget(self.frame)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 60, 281, 51))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pRecord = QtGui.QPushButton(self.layoutWidget1)
        self.pRecord.setMinimumSize(QtCore.QSize(0, 40))
        self.pRecord.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pRecord.setFont(font)
        self.pRecord.setStatusTip(_fromUtf8(""))
        self.pRecord.setText(_fromUtf8(""))
        self.pRecord.setCheckable(True)
        self.pRecord.setChecked(False)
        self.pRecord.setObjectName(_fromUtf8("pRecord"))
        self.horizontalLayout_5.addWidget(self.pRecord)
        self.pSaveState = QtGui.QPushButton(self.layoutWidget1)
        self.pSaveState.setMinimumSize(QtCore.QSize(0, 40))
        self.pSaveState.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pSaveState.setFont(font)
        self.pSaveState.setStatusTip(_fromUtf8(""))
        self.pSaveState.setText(_fromUtf8(""))
        self.pSaveState.setCheckable(False)
        self.pSaveState.setChecked(False)
        self.pSaveState.setObjectName(_fromUtf8("pSaveState"))
        self.horizontalLayout_5.addWidget(self.pSaveState)
        self.gridLayout_5.addWidget(self.frame, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBoxMonitoring = QtGui.QGroupBox(self.tMain)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBoxMonitoring.setFont(font)
        self.groupBoxMonitoring.setObjectName(_fromUtf8("groupBoxMonitoring"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBoxMonitoring)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.graph_monitoring_plots = PlotWidget(self.groupBoxMonitoring)
        self.graph_monitoring_plots.setObjectName(_fromUtf8("graph_monitoring_plots"))
        self.verticalLayout_3.addWidget(self.graph_monitoring_plots)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 2, 1, 1)
        self._2 = QtGui.QVBoxLayout()
        self._2.setSpacing(0)
        self._2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self._2.setObjectName(_fromUtf8("_2"))
        spacerItem = QtGui.QSpacerItem(20, 15, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self._2.addItem(spacerItem)
        self.pStartMonitoring = QtGui.QPushButton(self.groupBoxMonitoring)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pStartMonitoring.sizePolicy().hasHeightForWidth())
        self.pStartMonitoring.setSizePolicy(sizePolicy)
        self.pStartMonitoring.setMinimumSize(QtCore.QSize(0, 30))
        self.pStartMonitoring.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pStartMonitoring.setFont(font)
        self.pStartMonitoring.setCheckable(False)
        self.pStartMonitoring.setObjectName(_fromUtf8("pStartMonitoring"))
        self._2.addWidget(self.pStartMonitoring)
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self._2.addItem(spacerItem1)
        self.pStopMonitoring = QtGui.QPushButton(self.groupBoxMonitoring)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pStopMonitoring.sizePolicy().hasHeightForWidth())
        self.pStopMonitoring.setSizePolicy(sizePolicy)
        self.pStopMonitoring.setMinimumSize(QtCore.QSize(0, 30))
        self.pStopMonitoring.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pStopMonitoring.setFont(font)
        self.pStopMonitoring.setObjectName(_fromUtf8("pStopMonitoring"))
        self._2.addWidget(self.pStopMonitoring)
        spacerItem2 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self._2.addItem(spacerItem2)
        self.pResetMonitoring = QtGui.QPushButton(self.groupBoxMonitoring)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pResetMonitoring.sizePolicy().hasHeightForWidth())
        self.pResetMonitoring.setSizePolicy(sizePolicy)
        self.pResetMonitoring.setMinimumSize(QtCore.QSize(0, 30))
        self.pResetMonitoring.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pResetMonitoring.setFont(font)
        self.pResetMonitoring.setObjectName(_fromUtf8("pResetMonitoring"))
        self._2.addWidget(self.pResetMonitoring)
        spacerItem3 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self._2.addItem(spacerItem3)
        self.label_8 = QtGui.QLabel(self.groupBoxMonitoring)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self._2.addWidget(self.label_8)
        self.edit_alarm660 = QtGui.QLineEdit(self.groupBoxMonitoring)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_alarm660.sizePolicy().hasHeightForWidth())
        self.edit_alarm660.setSizePolicy(sizePolicy)
        self.edit_alarm660.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.edit_alarm660.setFont(font)
        self.edit_alarm660.setText(_fromUtf8(""))
        self.edit_alarm660.setPlaceholderText(_fromUtf8(""))
        self.edit_alarm660.setObjectName(_fromUtf8("edit_alarm660"))
        self._2.addWidget(self.edit_alarm660)
        spacerItem4 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self._2.addItem(spacerItem4)
        self.label_15 = QtGui.QLabel(self.groupBoxMonitoring)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self._2.addWidget(self.label_15)
        self.edit_alarm400 = QtGui.QLineEdit(self.groupBoxMonitoring)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_alarm400.sizePolicy().hasHeightForWidth())
        self.edit_alarm400.setSizePolicy(sizePolicy)
        self.edit_alarm400.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.edit_alarm400.setFont(font)
        self.edit_alarm400.setText(_fromUtf8(""))
        self.edit_alarm400.setPlaceholderText(_fromUtf8(""))
        self.edit_alarm400.setObjectName(_fromUtf8("edit_alarm400"))
        self._2.addWidget(self.edit_alarm400)
        self.gridLayout_3.addLayout(self._2, 0, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBoxMonitoring)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.combo_selected_image = QtGui.QComboBox(self.tMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_selected_image.sizePolicy().hasHeightForWidth())
        self.combo_selected_image.setSizePolicy(sizePolicy)
        self.combo_selected_image.setMinimumSize(QtCore.QSize(150, 0))
        self.combo_selected_image.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.combo_selected_image.setFont(font)
        self.combo_selected_image.setFrame(True)
        self.combo_selected_image.setObjectName(_fromUtf8("combo_selected_image"))
        self.horizontalLayout_8.addWidget(self.combo_selected_image)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem6 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.lValue = QtGui.QLabel(self.tMain)
        self.lValue.setMinimumSize(QtCore.QSize(250, 0))
        self.lValue.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lValue.setFont(font)
        self.lValue.setText(_fromUtf8(""))
        self.lValue.setObjectName(_fromUtf8("lValue"))
        self.horizontalLayout.addWidget(self.lValue)
        self.horizontalLayout_8.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.gridLayout_5.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.groupBoxSuperposition = QtGui.QGroupBox(self.tMain)
        self.groupBoxSuperposition.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBoxSuperposition.setFont(font)
        self.groupBoxSuperposition.setObjectName(_fromUtf8("groupBoxSuperposition"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxSuperposition)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.graph_image_superposition = ImageView(self.groupBoxSuperposition)
        self.graph_image_superposition.setMinimumSize(QtCore.QSize(0, 0))
        self.graph_image_superposition.setObjectName(_fromUtf8("graph_image_superposition"))
        self.gridLayout_2.addWidget(self.graph_image_superposition, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBoxSuperposition)
        self.groupBox = QtGui.QGroupBox(self.tMain)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.graph_image = ImageView(self.groupBox)
        self.graph_image.setMinimumSize(QtCore.QSize(0, 0))
        self.graph_image.setObjectName(_fromUtf8("graph_image"))
        self.gridLayout.addWidget(self.graph_image, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 1, 0, 1, 2)
        self.tabWidget.addTab(self.tMain, _fromUtf8(""))
        self.tSettings = QtGui.QWidget()
        self.tSettings.setObjectName(_fromUtf8("tSettings"))
        self.groupBoxProtocol = QtGui.QGroupBox(self.tSettings)
        self.groupBoxProtocol.setGeometry(QtCore.QRect(20, 10, 501, 141))
        self.groupBoxProtocol.setObjectName(_fromUtf8("groupBoxProtocol"))
        self.label_2 = QtGui.QLabel(self.groupBoxProtocol)
        self.label_2.setGeometry(QtCore.QRect(31, 31, 183, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.eLoggingFolder = QtGui.QLineEdit(self.groupBoxProtocol)
        self.eLoggingFolder.setGeometry(QtCore.QRect(220, 28, 133, 20))
        self.eLoggingFolder.setObjectName(_fromUtf8("eLoggingFolder"))
        self.label_3 = QtGui.QLabel(self.groupBoxProtocol)
        self.label_3.setGeometry(QtCore.QRect(31, 70, 157, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.sTimer = QtGui.QSpinBox(self.groupBoxProtocol)
        self.sTimer.setGeometry(QtCore.QRect(210, 68, 51, 20))
        self.sTimer.setMaximum(10000)
        self.sTimer.setProperty("value", 2)
        self.sTimer.setObjectName(_fromUtf8("sTimer"))
        self.label_4 = QtGui.QLabel(self.groupBoxProtocol)
        self.label_4.setGeometry(QtCore.QRect(270, 70, 16, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.pSaveResults = QtGui.QPushButton(self.groupBoxProtocol)
        self.pSaveResults.setGeometry(QtCore.QRect(370, 28, 75, 23))
        self.pSaveResults.setObjectName(_fromUtf8("pSaveResults"))
        self.cFullProtocolSave = QtGui.QCheckBox(self.groupBoxProtocol)
        self.cFullProtocolSave.setGeometry(QtCore.QRect(30, 110, 221, 17))
        self.cFullProtocolSave.setChecked(False)
        self.cFullProtocolSave.setObjectName(_fromUtf8("cFullProtocolSave"))
        self.pCalibration = QtGui.QPushButton(self.tSettings)
        self.pCalibration.setEnabled(True)
        self.pCalibration.setGeometry(QtCore.QRect(530, 10, 271, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pCalibration.setFont(font)
        self.pCalibration.setObjectName(_fromUtf8("pCalibration"))
        self.groupBoxRezime = QtGui.QGroupBox(self.tSettings)
        self.groupBoxRezime.setEnabled(True)
        self.groupBoxRezime.setGeometry(QtCore.QRect(20, 160, 851, 341))
        self.groupBoxRezime.setObjectName(_fromUtf8("groupBoxRezime"))
        self.label_5 = QtGui.QLabel(self.groupBoxRezime)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 251, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBoxRezime)
        self.label_6.setGeometry(QtCore.QRect(20, 70, 261, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBoxRezime)
        self.label_7.setGeometry(QtCore.QRect(20, 110, 231, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.e400Exposition = QtGui.QLineEdit(self.groupBoxRezime)
        self.e400Exposition.setGeometry(QtCore.QRect(310, 30, 113, 25))
        self.e400Exposition.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.e400Exposition.setObjectName(_fromUtf8("e400Exposition"))
        self.e660Exposition = QtGui.QLineEdit(self.groupBoxRezime)
        self.e660Exposition.setGeometry(QtCore.QRect(310, 70, 113, 25))
        self.e660Exposition.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.e660Exposition.setObjectName(_fromUtf8("e660Exposition"))
        self.e740Exposition = QtGui.QLineEdit(self.groupBoxRezime)
        self.e740Exposition.setGeometry(QtCore.QRect(310, 110, 113, 25))
        self.e740Exposition.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.e740Exposition.setObjectName(_fromUtf8("e740Exposition"))
        self.eCameraExposition = QtGui.QLineEdit(self.groupBoxRezime)
        self.eCameraExposition.setEnabled(False)
        self.eCameraExposition.setGeometry(QtCore.QRect(310, 190, 113, 25))
        self.eCameraExposition.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.eCameraExposition.setObjectName(_fromUtf8("eCameraExposition"))
        self.label_9 = QtGui.QLabel(self.groupBoxRezime)
        self.label_9.setGeometry(QtCore.QRect(20, 190, 221, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.groupBoxRezime)
        self.label_10.setGeometry(QtCore.QRect(20, 150, 221, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.ePeriod = QtGui.QLineEdit(self.groupBoxRezime)
        self.ePeriod.setEnabled(False)
        self.ePeriod.setGeometry(QtCore.QRect(310, 150, 113, 22))
        self.ePeriod.setStatusTip(_fromUtf8(""))
        self.ePeriod.setWhatsThis(_fromUtf8(""))
        self.ePeriod.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ePeriod.setPlaceholderText(_fromUtf8(""))
        self.ePeriod.setObjectName(_fromUtf8("ePeriod"))
        self.label_11 = QtGui.QLabel(self.groupBoxRezime)
        self.label_11.setGeometry(QtCore.QRect(20, 230, 221, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.eCameraGain = QtGui.QLineEdit(self.groupBoxRezime)
        self.eCameraGain.setGeometry(QtCore.QRect(310, 230, 71, 24))
        self.eCameraGain.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.eCameraGain.setObjectName(_fromUtf8("eCameraGain"))
        self.label_12 = QtGui.QLabel(self.groupBoxRezime)
        self.label_12.setGeometry(QtCore.QRect(390, 234, 221, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.cNoneNormilize = QtGui.QCheckBox(self.groupBoxRezime)
        self.cNoneNormilize.setGeometry(QtCore.QRect(440, 230, 261, 20))
        self.cNoneNormilize.setChecked(True)
        self.cNoneNormilize.setObjectName(_fromUtf8("cNoneNormilize"))
        self.pBlueSingle = QtGui.QPushButton(self.groupBoxRezime)
        self.pBlueSingle.setGeometry(QtCore.QRect(440, 30, 261, 25))
        self.pBlueSingle.setObjectName(_fromUtf8("pBlueSingle"))
        self.pRedSingle = QtGui.QPushButton(self.groupBoxRezime)
        self.pRedSingle.setGeometry(QtCore.QRect(440, 70, 261, 25))
        self.pRedSingle.setObjectName(_fromUtf8("pRedSingle"))
        self.pIRSingle = QtGui.QPushButton(self.groupBoxRezime)
        self.pIRSingle.setGeometry(QtCore.QRect(440, 110, 261, 25))
        self.pIRSingle.setObjectName(_fromUtf8("pIRSingle"))
        self.pNoneSingle = QtGui.QPushButton(self.groupBoxRezime)
        self.pNoneSingle.setGeometry(QtCore.QRect(440, 190, 261, 25))
        self.pNoneSingle.setObjectName(_fromUtf8("pNoneSingle"))
        self.label_13 = QtGui.QLabel(self.groupBoxRezime)
        self.label_13.setGeometry(QtCore.QRect(20, 270, 221, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.cCameraBit = QtGui.QComboBox(self.groupBoxRezime)
        self.cCameraBit.setGeometry(QtCore.QRect(310, 270, 73, 25))
        self.cCameraBit.setObjectName(_fromUtf8("cCameraBit"))
        self.cCameraBit.addItem(_fromUtf8(""))
        self.cCameraBit.addItem(_fromUtf8(""))
        self.label_14 = QtGui.QLabel(self.groupBoxRezime)
        self.label_14.setGeometry(QtCore.QRect(20, 315, 221, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.cCameraBinning = QtGui.QComboBox(self.groupBoxRezime)
        self.cCameraBinning.setGeometry(QtCore.QRect(311, 310, 181, 25))
        self.cCameraBinning.setObjectName(_fromUtf8("cCameraBinning"))
        self.groupBoxLedSources = QtGui.QGroupBox(self.groupBoxRezime)
        self.groupBoxLedSources.setGeometry(QtCore.QRect(720, 20, 101, 151))
        self.groupBoxLedSources.setObjectName(_fromUtf8("groupBoxLedSources"))
        self.widget_led740 = QLed(self.groupBoxLedSources)
        self.widget_led740.setGeometry(QtCore.QRect(30, 100, 41, 31))
        self.widget_led740.setObjectName(_fromUtf8("widget_led740"))
        self.widget_led400 = QLed(self.groupBoxLedSources)
        self.widget_led400.setGeometry(QtCore.QRect(30, 20, 41, 31))
        self.widget_led400.setObjectName(_fromUtf8("widget_led400"))
        self.widget_led660 = QLed(self.groupBoxLedSources)
        self.widget_led660.setGeometry(QtCore.QRect(30, 60, 41, 31))
        self.widget_led660.setObjectName(_fromUtf8("widget_led660"))
        self.pLiveMode = QtGui.QPushButton(self.tSettings)
        self.pLiveMode.setGeometry(QtCore.QRect(530, 90, 271, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pLiveMode.setFont(font)
        self.pLiveMode.setObjectName(_fromUtf8("pLiveMode"))
        self.groupWatch = QtGui.QGroupBox(self.tSettings)
        self.groupWatch.setGeometry(QtCore.QRect(20, 620, 851, 91))
        self.groupWatch.setObjectName(_fromUtf8("groupWatch"))
        self.rShadowingNone = QtGui.QRadioButton(self.groupWatch)
        self.rShadowingNone.setGeometry(QtCore.QRect(10, 30, 95, 20))
        self.rShadowingNone.setChecked(False)
        self.rShadowingNone.setObjectName(_fromUtf8("rShadowingNone"))
        self.rShadowingGlare = QtGui.QRadioButton(self.groupWatch)
        self.rShadowingGlare.setGeometry(QtCore.QRect(10, 60, 321, 20))
        self.rShadowingGlare.setChecked(True)
        self.rShadowingGlare.setObjectName(_fromUtf8("rShadowingGlare"))
        self.groupBeep = QtGui.QGroupBox(self.tSettings)
        self.groupBeep.setGeometry(QtCore.QRect(20, 510, 291, 91))
        self.groupBeep.setObjectName(_fromUtf8("groupBeep"))
        self.label_16 = QtGui.QLabel(self.groupBeep)
        self.label_16.setGeometry(QtCore.QRect(250, 22, 121, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.groupBeep)
        self.label_17.setGeometry(QtCore.QRect(11, 22, 157, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.sTimerBeep = QtGui.QSpinBox(self.groupBeep)
        self.sTimerBeep.setGeometry(QtCore.QRect(190, 20, 51, 20))
        self.sTimerBeep.setMinimum(1)
        self.sTimerBeep.setMaximum(10000)
        self.sTimerBeep.setProperty("value", 60)
        self.sTimerBeep.setObjectName(_fromUtf8("sTimerBeep"))
        self.cResetBeepTimer = QtGui.QCheckBox(self.groupBeep)
        self.cResetBeepTimer.setGeometry(QtCore.QRect(10, 50, 371, 17))
        self.cResetBeepTimer.setChecked(True)
        self.cResetBeepTimer.setObjectName(_fromUtf8("cResetBeepTimer"))
        self.groupBeep_3 = QtGui.QGroupBox(self.tSettings)
        self.groupBeep_3.setGeometry(QtCore.QRect(350, 510, 291, 91))
        self.groupBeep_3.setObjectName(_fromUtf8("groupBeep_3"))
        self.cAutoLevel = QtGui.QCheckBox(self.groupBeep_3)
        self.cAutoLevel.setGeometry(QtCore.QRect(10, 20, 371, 17))
        self.cAutoLevel.setChecked(False)
        self.cAutoLevel.setObjectName(_fromUtf8("cAutoLevel"))
        self.tabWidget.addTab(self.tSettings, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.cCameraBit.setCurrentIndex(1)
        self.cCameraBinning.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Флуорометр", None))
        self.label_region_defined.setText(_translate("Form", "Область свечения не определена", None))
        self.label_properties.setText(_translate("Form", "________________________________________________________", None))
        self.groupProtocol.setTitle(_translate("Form", "Работа с протоколами", None))
        self.pLoadExperiment.setText(_translate("Form", "Загрузка протокола", None))
        self.pStart.setText(_translate("Form", "СТАРТ", None))
        self.label_status.setText(_translate("Form", ".", None))
        self.edit_full_name.setPlaceholderText(_translate("Form", "Фамилия Имя Отчество", None))
        self.pManual.setText(_translate("Form", "Ручной ввод областей", None))
        self.pResetRegion.setText(_translate("Form", "Сброс областей", None))
        self.pRecord.setToolTip(_translate("Form", "Протоколирование", None))
        self.pSaveState.setToolTip(_translate("Form", "Сохранить текущие кадры", None))
        self.groupBoxMonitoring.setTitle(_translate("Form", "Мониторинг ФДТ", None))
        self.pStartMonitoring.setText(_translate("Form", "Старт", None))
        self.pStopMonitoring.setText(_translate("Form", "Стоп", None))
        self.pResetMonitoring.setText(_translate("Form", "Сброс", None))
        self.label_8.setText(_translate("Form", "Порог 660 нм", None))
        self.label_15.setText(_translate("Form", "Порог 400 нм", None))
        self.groupBoxSuperposition.setTitle(_translate("Form", "Наложенное изображение", None))
        self.groupBox.setTitle(_translate("Form", "Флуоресцентное изображение", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tMain), _translate("Form", "Основное", None))
        self.groupBoxProtocol.setTitle(_translate("Form", "Параметры протоколирования", None))
        self.label_2.setText(_translate("Form", "Папка для сохранения результатов", None))
        self.eLoggingFolder.setText(_translate("Form", "Результат", None))
        self.label_3.setText(_translate("Form", "Сохранять состояние каждые ", None))
        self.label_4.setText(_translate("Form", "c", None))
        self.pSaveResults.setText(_translate("Form", "...", None))
        self.cFullProtocolSave.setText(_translate("Form", "Сохранять полный протокол?", None))
        self.pCalibration.setText(_translate("Form", "Калибровка\n"
" размера кадра", None))
        self.groupBoxRezime.setTitle(_translate("Form", "Режим работы регистрации изображений", None))
        self.label_5.setText(_translate("Form", "Время свечения диода 400 нм (синий), c", None))
        self.label_6.setText(_translate("Form", "Время свечения диода 660 нм (красный), c", None))
        self.label_7.setText(_translate("Form", "Время свечения диода 740 нм (ИК), c", None))
        self.e400Exposition.setToolTip(_translate("Form", ">= 0.001 c", None))
        self.e400Exposition.setText(_translate("Form", "0.3", None))
        self.e660Exposition.setToolTip(_translate("Form", ">= 0.001 c", None))
        self.e660Exposition.setText(_translate("Form", "0.3", None))
        self.e740Exposition.setToolTip(_translate("Form", ">= 0.001 c", None))
        self.e740Exposition.setText(_translate("Form", "0.001", None))
        self.eCameraExposition.setToolTip(_translate("Form", "Должен быть >= 0.07 c и меньше, чем период переключения диодов", None))
        self.eCameraExposition.setText(_translate("Form", "0.3", None))
        self.label_9.setText(_translate("Form", "Экспозиция камеры, c", None))
        self.label_10.setText(_translate("Form", "Период переключения диодов, c", None))
        self.ePeriod.setToolTip(_translate("Form", "Должен быть >= 0.1 c и больше, чем экспозиция камеры ", None))
        self.ePeriod.setText(_translate("Form", "0.35", "Не ниже 0.1"))
        self.label_11.setText(_translate("Form", "Усиление камеры", None))
        self.eCameraGain.setToolTip(_translate("Form", "от 15 до 41 дБ", None))
        self.eCameraGain.setText(_translate("Form", "15", None))
        self.label_12.setText(_translate("Form", "дБ", None))
        self.cNoneNormilize.setText(_translate("Form", "Вычитать \"темновой\" кадр", None))
        self.pBlueSingle.setText(_translate("Form", "Получить одиночный кадр с ист. 400 нм", None))
        self.pRedSingle.setText(_translate("Form", "Получить одиночный кадр с ист. 660 нм", None))
        self.pIRSingle.setText(_translate("Form", "Получить одиночный кадр с ист. 740 нм", None))
        self.pNoneSingle.setText(_translate("Form", "Получить одиночный \"темновой\" кадр", None))
        self.label_13.setText(_translate("Form", "Битность изображения", None))
        self.cCameraBit.setItemText(0, _translate("Form", "8 бит", None))
        self.cCameraBit.setItemText(1, _translate("Form", "12 бит", None))
        self.label_14.setText(_translate("Form", "Биннинг изображения", None))
        self.groupBoxLedSources.setTitle(_translate("Form", "Вкл. источник", None))
        self.pLiveMode.setText(_translate("Form", "Включить режим \n"
"LiveMode", None))
        self.groupWatch.setTitle(_translate("Form", "Слежение за положением флуоресцентной области при мониторинге", None))
        self.rShadowingNone.setText(_translate("Form", "Отключено", None))
        self.rShadowingGlare.setText(_translate("Form", "По области свечения терапевтического лазера", None))
        self.groupBeep.setTitle(_translate("Form", "Звуковой сигнал во время процедуры ФДТ", None))
        self.label_16.setText(_translate("Form", "c", None))
        self.label_17.setText(_translate("Form", "Проигрывать сигнал каждые", None))
        self.cResetBeepTimer.setText(_translate("Form", "Сбрасывать таймер при выключении лазера", None))
        self.groupBeep_3.setTitle(_translate("Form", "Настройки интерфейса", None))
        self.cAutoLevel.setText(_translate("Form", "Автоматический уровень изображений", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tSettings), _translate("Form", "Параметры", None))

from QLed import QLed
from pyqtgraph import ImageView, PlotWidget
